### ISSUE TITLE
Cover the `crowdin.ts` class by Unit tests

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-apps-functions#21]
This class is an important part of the application, so it would be great to have Unit tests for its methods.

- [Actual coverage](https://app.codecov.io/gh/crowdin/crowdin-apps-functions/blob/main/src/crowdin.ts)
- [crowdin.ts](https://github.com/crowdin/crowdin-apps-functions/blob/main/src/crowdin.ts)

**Comment by MaurizioPz** [comment]
Hi @andrii-bodnar I think I can work on this, can you assign it to me?
thanks

**Comment by andrii-bodnar** [comment]
Hi @MaurizioPz, sure, thank you!
